name: urban_cafe
description: "Urban Cafe"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.3
  file_picker: ^10.3.7
  crop_your_image: ^2.0.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  go_router: ^14.2.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/urbancafe_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logos/urbancafe_logo.png"
    background_color: "#F7F7F7" # Matches your AppTheme.neutralBg
    theme_color: "#8B5E3C"      # Matches your AppTheme.primary
  windows:
    generate: true
    image_path: "assets/logos/urbancafe_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logos/urbancafe_logo.png"


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
  #  - .env
    - assets/logos/
  #   - images/a_dot_ham.jpeg


