name: urban_cafe
description: "Urban Cafe"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.2.0+4

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.3
  file_picker: ^10.3.10
  crop_your_image: ^2.0.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  go_router: ^17.1.0
  google_fonts: ^7.0.0
  skeletonizer: ^2.1.3
  font_awesome_flutter: ^10.12.0
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  http: ^1.6.0
  web: ^1.1.1
  flutter_secure_storage: ^10.0.0
  fpdart: ^1.2.0
  equatable: ^2.0.8
  timeago: ^3.7.1
  easy_localization: ^3.0.8
  fl_chart: ^1.1.1
  get_it: ^9.2.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0
  connectivity_plus: ^7.0.0
  uuid: ^4.5.2
  path: ^1.9.1
  flutter_cache_manager: ^3.4.1
  image: ^4.8.0
  sqlite3: ^3.1.6
  path_provider: ^2.1.5
  rename: ^3.1.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/urbancafe_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logos/urbancafe_logo.png"
    background_color: "#F7F7F7"
    theme_color: "#8B5E3C"
  windows:
    generate: true
    image_path: "assets/logos/urbancafe_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logos/urbancafe_logo.png"


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    # - .env
    - assets/logos/
    - assets/translations/
  #   - images/a_dot_ham.jpeg


